# Generated by Django 4.2 on 2025-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chat Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('education', 'Education'), ('financial', 'Financial Help'), ('empowerment', 'Women Empowerment'), ('health', 'Health'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=100)),
                ('income_limit', models.IntegerField(default=9999999)),
                ('gender', models.CharField(choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male')], default='any', max_length=10)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
                'ordering': ['category', 'name'],
            },
        ),
    ]
