# Generated by Django 4.2 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="category",
            field=models.CharField(
                choices=[
                    ("education", "Education"),
                    ("financial", "Financial Support"),
                    ("health", "Health"),
                    ("employment", "Jobs and Skills"),
                    ("empowerment", "Empowerment"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
