# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women_app", "0002_alter_scheme_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="matched_scheme_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="needs_human_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="recommended_scheme_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="source",
            field=models.CharField(choices=[("chat", "Chat"), ("wizard", "Eligibility Wizard")], default="chat", max_length=20),
        ),
        migrations.AddField(
            model_name="scheme",
            name="beneficiary_tags",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scheme",
            name="district_coverage",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scheme",
            name="effort_level",
            field=models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=20),
        ),
        migrations.AddField(
            model_name="scheme",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="helpline",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="scheme",
            name="last_verified_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="offline_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="scheme",
            name="official_source_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="scheme",
            name="required_documents",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="state_coverage",
            field=models.CharField(default="All India", max_length=255),
        ),
        migrations.AddField(
            model_name="scheme",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="verification_status",
            field=models.CharField(choices=[("verified", "Verified"), ("review_required", "Review Required"), ("stale", "Stale"), ("broken", "Broken Link")], default="review_required", max_length=30),
        ),
        migrations.AddField(
            model_name="scheme",
            name="where_to_apply",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveIntegerField(default=200)),
                ("actor", models.CharField(blank=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EligibilityAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(default="en", max_length=10)),
                ("age", models.PositiveIntegerField()),
                ("annual_income", models.PositiveIntegerField(blank=True, null=True)),
                ("income_band", models.CharField(choices=[("under_1l", "Under Rs 1 lakh"), ("under_2l", "Under Rs 2 lakh"), ("under_5l", "Under Rs 5 lakh"), ("under_8l", "Under Rs 8 lakh"), ("above_8l", "Above Rs 8 lakh")], max_length=30)),
                ("gender", models.CharField(choices=[("female", "Female"), ("male", "Male"), ("any", "Prefer not to say")], default="female", max_length=10)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("residence_type", models.CharField(choices=[("rural", "Rural"), ("urban", "Urban"), ("semi_urban", "Semi Urban")], max_length=20)),
                ("support_need", models.CharField(max_length=50)),
                ("is_student", models.BooleanField(default=False)),
                ("is_mother", models.BooleanField(default=False)),
                ("is_entrepreneur", models.BooleanField(default=False)),
                ("has_disability", models.BooleanField(default=False)),
                ("caste_category", models.CharField(choices=[("general", "General"), ("sc", "SC"), ("st", "ST"), ("obc", "OBC"), ("ews", "EWS"), ("minority", "Minority"), ("other", "Other")], default="general", max_length=20)),
                ("document_readiness", models.CharField(choices=[("ready", "All documents ready"), ("partial", "Some documents ready"), ("not_ready", "Need document help")], max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("recommendation_count", models.PositiveIntegerField(default=0)),
                ("recommended_scheme_names", models.JSONField(blank=True, default=list)),
                ("needs_human_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Eligibility Assessment",
                "verbose_name_plural": "Eligibility Assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("preferred_language", models.CharField(default="en", max_length=10)),
                ("support_type", models.CharField(choices=[("ngo_worker", "NGO Worker"), ("shg_volunteer", "SHG Volunteer"), ("callback", "Support Callback")], max_length=30)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField()),
                ("status", models.CharField(choices=[("new", "New"), ("in_progress", "In Progress"), ("resolved", "Resolved")], default="new", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Escalation Request",
                "verbose_name_plural": "Escalation Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
