# Generated by Django 4.2 on 2026-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0003_product_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityassessment',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('any', 'Prefer not to say')], default='any', max_length=10),
        ),
    ]
