# Generated by Django 4.2 on 2026-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0004_inclusive_defaults'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='women_app_a_created_2babaa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['path', 'method', '-created_at'], name='women_app_a_path_c70226_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status_code', '-created_at'], name='women_app_a_status__e7bcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['-created_at'], name='women_app_c_created_55b133_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['source', 'needs_human_review', '-created_at'], name='women_app_c_source_c354c1_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['language', '-created_at'], name='women_app_c_languag_3a4b69_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityassessment',
            index=models.Index(fields=['-created_at'], name='women_app_e_created_0ef6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityassessment',
            index=models.Index(fields=['state', 'support_need'], name='women_app_e_state_e1ef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityassessment',
            index=models.Index(fields=['needs_human_review', '-created_at'], name='women_app_e_needs_h_f2191b_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationrequest',
            index=models.Index(fields=['status', '-created_at'], name='women_app_e_status_67f680_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationrequest',
            index=models.Index(fields=['state', 'status'], name='women_app_e_state_53f907_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['category', 'name'], name='women_app_s_categor_a1dc17_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['verification_status', 'last_verified_on'], name='women_app_s_verific_6946d3_idx'),
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['gender', 'category'], name='women_app_s_gender_9bb571_idx'),
        ),
    ]
