# Generated by Django 4.2 on 2026-03-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0005_auditlog_women_app_a_created_2babaa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='district_coverage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='state_coverage',
            field=models.TextField(default='All India'),
        ),
    ]
