# Generated by Django 4.2 on 2026-03-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women_app', '0006_alter_scheme_district_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationrequest',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalationrequest',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escalationrequest',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='escalationrequest',
            index=models.Index(fields=['status', 'due_at'], name='women_app_e_status_ace50c_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='women_app_e_assigne_c396ec_idx'),
        ),
    ]
