# Generated by Django 4.2 on 2026-03-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('women_app', '0007_escalationrequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('agriculture', 'Agriculture'), ('financial', 'Financial Support'), ('health', 'Health'), ('employment', 'Jobs and Skills'), ('empowerment', 'Empowerment'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_income', models.PositiveIntegerField(blank=True, null=True)),
                ('income_band', models.CharField(choices=[('under_1l', 'Under Rs 1 lakh'), ('under_2l', 'Under Rs 2 lakh'), ('under_5l', 'Under Rs 5 lakh'), ('under_8l', 'Under Rs 8 lakh'), ('above_8l', 'Above Rs 8 lakh')], default='under_5l', max_length=30)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('any', 'Prefer not to say')], default='any', max_length=10)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('residence_type', models.CharField(choices=[('rural', 'Rural'), ('urban', 'Urban'), ('semi_urban', 'Semi Urban')], default='urban', max_length=20)),
                ('support_need', models.CharField(default='other', max_length=50)),
                ('is_student', models.BooleanField(default=False)),
                ('is_mother', models.BooleanField(default=False)),
                ('is_entrepreneur', models.BooleanField(default=False)),
                ('has_disability', models.BooleanField(default=False)),
                ('caste_category', models.CharField(choices=[('general', 'General'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('ews', 'EWS'), ('minority', 'Minority'), ('other', 'Other')], default='general', max_length=20)),
                ('document_readiness', models.CharField(choices=[('ready', 'All documents ready'), ('partial', 'Some documents ready'), ('not_ready', 'Need document help')], default='partial', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Citizen Profile',
                'verbose_name_plural': 'Citizen Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
