# Generated by Django 4.2 on 2026-03-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women_app', '0008_alter_scheme_category_citizenprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('scheme_name', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='women_app.citizenprofile')),
            ],
            options={
                'verbose_name': 'Citizen Application',
                'verbose_name_plural': 'Citizen Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='women_app.citizenapplication')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='women_app.citizenprofile')),
            ],
            options={
                'verbose_name': 'Citizen Document',
                'verbose_name_plural': 'Citizen Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='citizendocument',
            index=models.Index(fields=['verification_status', '-uploaded_at'], name='women_app_c_verific_89cbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='citizendocument',
            index=models.Index(fields=['profile', '-uploaded_at'], name='women_app_c_profile_e134d4_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='women_app_c_status_8e85ed_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenapplication',
            index=models.Index(fields=['profile', '-submitted_at'], name='women_app_c_profile_0eaa86_idx'),
        ),
    ]
