SUPPORTED_LANGUAGES = {
    "en": "English",
    "hi": "हिंदी",
    "mr": "मराठी",
}


UI_STRINGS = {
    "en": {
        "brand_name": "JanSetu",
        "brand_tagline": "Public Benefits Guide",
        "meta_description": "JanSetu helps people across India find verified government schemes, district-ready support paths, and official apply links in simple language.",
        "nav_wizard": "Guided Check",
        "nav_chat": "Ask AI",
        "nav_schemes": "Schemes",
        "nav_support": "Human Help",
        "nav_privacy": "Privacy",
        "lang_label": "Language",
        "footer_line": "Verified schemes, simple next steps, and human help when needed.",
        "comfort_off": "A+ Text",
        "comfort_on": "A- Text",
        "hero_eyebrow": "Inclusive government support finder",
        "hero_primary": "Start Eligibility Check",
        "hero_secondary": "Browse schemes",
        "promise_official_sources": "Official government sources",
        "promise_quick_links": "Quick apply links",
        "promise_human_help": "Human help when needed",
        "home_heading": "Find the Right Government Scheme in Minutes",
        "home_subtitle": "Use a calm guided flow, verified sources, and official next steps to reach the right benefit faster.",
        "home_search_placeholder": "Search scholarship, pension, health, loan, startup",
        "home_search_label": "Search schemes",
        "use_voice_chat": "Use voice or chat",
        "metric_schemes": "scheme records ready to explore",
        "metric_categories": "simple support categories",
        "metric_states": "state-aware guidance",
        "fast_path_label": "Fast path",
        "fast_path_title": "Best match in minutes",
        "fast_path_text": "No need to know the scheme name first.",
        "comfort_label": "Comfort",
        "comfort_title": "Large text and voice help",
        "made_for_label": "Made for first-time users",
        "made_for_text": "Large cards, simple language, direct next steps.",
        "choose_need_kicker": "Choose a need",
        "choose_need_title": "Start with one clear problem",
        "news_kicker": "Latest scheme updates",
        "news_title": "Daily government scheme news",
        "news_subtitle": "Fresh official updates on new schemes, approvals, and rollout changes.",
        "news_live_label": "Updated from PIB",
        "news_empty": "Fresh scheme news is not available right now.",
        "separate_features_kicker": "Why this feels simpler",
        "separate_features_title": "Everything is arranged to feel calm and easy",
        "how_it_works_kicker": "How it works",
        "how_it_works_title": "Three easy steps",
        "comfort_section_kicker": "Comfort",
        "comfort_section_title": "Designed for younger and older users",
        "featured_kicker": "Trusted picks",
        "featured_title": "Popular starting points",
        "trusted_source": "Trusted source",
        "wizard_title": "Guided eligibility check",
        "wizard_heading": "Let's find what you're eligible for.",
        "wizard_subtitle": "We ask only what matters so new users can finish quickly and feel confident.",
        "wizard_promise_1": "3 gentle steps",
        "wizard_promise_2": "Simple language",
        "wizard_promise_3": "Official links after matching",
        "wizard_step_1": "1. Basic details",
        "wizard_step_2": "2. Who needs help",
        "wizard_step_3": "3. Final checks",
        "wizard_focus_title": "Choose the person or support you want help for",
        "wizard_focus_help": "Tap one option. We will set the right scheme path for you.",
        "wizard_submit": "See recommendations",
        "wizard_side_kicker": "Good to know",
        "wizard_side_title": "You do not need to be perfect",
        "wizard_result_title": "Your best next steps",
        "wizard_empty": "No strong match yet. Human help is the better next step.",
        "matches_found": "helpful matches found",
        "next_step_label": "Next step",
        "effort_label": "Estimated effort",
        "documents_label": "Documents",
        "documents_fallback": "Open the official scheme page for the latest document list.",
        "chat_title": "Guided voice and chat",
        "chat_heading": "Ask in your own words.",
        "chat_subtitle": "Speak or type in simple words. The assistant follows your selected language and suggests the next step.",
        "chat_promise_1": "No long form",
        "chat_promise_2": "Prompt examples included",
        "chat_promise_3": "Open scheme details in one tap",
        "chat_assistant_title": "JanSetu assistant",
        "chat_assistant_subtitle": "Speak in plain words like you would ask a helpful person.",
        "chat_placeholder": "Example: I am 26, income 2 lakh, from Maharashtra, and need scholarship help",
        "chat_best_for_kicker": "Best for",
        "chat_best_for_title": "When chat is easier",
        "prefer_wizard": "Prefer step-by-step guidance",
        "voice_listen": "Speak",
        "voice_stop": "Stop",
        "voice_read": "Read reply",
        "voice_listening": "Listening...",
        "send": "Send",
        "chat_intro": "Share your age, income, state, and need. I will look for the most relevant schemes first.",
        "chat_error": "Something went wrong while checking the scheme list.",
        "chat_retry": "I could not generate a reply just now. Please try again.",
        "chat_connection_failed": "The connection failed. Please retry in a moment.",
        "chat_open_details": "Open details",
        "chat_official_source": "Official source",
        "chat_human_title": "Need human help?",
        "chat_human_text": "Open the Human Help page to request callback support.",
        "support_request_link": "Request support",
        "support_title": "Request human help",
        "support_heading": "Get a real person to help when the journey feels hard.",
        "support_subtitle": "If the rules are confusing, documents are missing, or you want someone to guide you, request support here.",
        "support_submit": "Request support",
        "support_success": "Support request saved. A person can now follow up.",
        "support_reasons_kicker": "Good reasons to ask",
        "support_reasons_title": "Use human help when",
        "schemes_title": "Verified scheme explorer",
        "schemes_heading": "Browse trusted schemes without getting overwhelmed.",
        "schemes_subtitle": "Search official records, filter by need, and open a clear detail page with next steps.",
        "catalogue_records": "records in this catalogue",
        "simple_categories": "simple categories",
        "current_page": "current page",
        "schemes_search_placeholder": "Search by scheme, benefit, ministry, tag, or need",
        "filter_all_categories": "All categories",
        "filter_all_states": "All states",
        "apply_filters": "Apply filters",
        "what_to_do_next": "What to do next",
        "official_source_pending": "Official source pending",
        "no_matching_schemes": "No matching schemes yet",
        "no_matching_schemes_help": "Try broader words like scholarship, health, pension, business, job, or disability support.",
        "previous": "Previous",
        "next": "Next",
        "page_of": "Page {current} of {total}",
        "scheme_details_kicker": "Scheme details",
        "quick_links_kicker": "Quick links",
        "quick_links_title": "Open the right place fast",
        "detail_apply_card_kicker": "Apply now",
        "detail_apply_card_title": "Start from the safest official link",
        "detail_apply_card_text": "Use the official source first, then keep the documents below ready before you begin.",
        "detail_source_label": "Source",
        "detail_eligibility_label": "Eligibility",
        "detail_benefits_label": "Benefits",
        "detail_apply_label": "How to apply",
        "detail_last_verified_label": "Last verified",
        "detail_where_to_apply_label": "Where to apply",
        "detail_effort_level_label": "Effort level",
        "detail_coverage_label": "Coverage",
        "detail_documents_kicker": "Documents",
        "detail_documents_title": "Keep these ready",
        "detail_faq_kicker": "FAQs",
        "detail_faq_title": "Common questions",
        "detail_documents_fallback": "Open the official page to see the latest required documents.",
        "detail_faq_fallback": "No FAQ items were available for this scheme right now.",
        "open_official_page": "Official page",
        "not_set": "Not set",
        "detail_apply_fallback": "Check the official page above.",
        "scheme_apply_fallback": "Open the official page for the latest application steps.",
        "privacy_title": "Privacy and responsible use",
        "privacy_subtitle": "This service stores only what is needed to improve support, review quality, and follow up on requests.",
        "privacy_store_title": "What this service stores",
        "privacy_use_title": "How the data should be used",
        "ops_title": "Operations dashboard",
        "ops_subtitle": "Monitor unanswered requests, stale scheme records, link issues, and demand trends.",
        "select_state": "Select state",
        "select_district": "Select district",
        "select_need_focus": "Choose one option",
    },
    "hi": {
        "brand_name": "जनसेतु",
        "brand_tagline": "सरकारी सहायता मार्गदर्शक",
        "meta_description": "जनसेतु भारत भर के लोगों को सत्यापित सरकारी योजनाएं, स्पष्ट अगले कदम और आधिकारिक आवेदन लिंक सरल भाषा में ढूंढने में मदद करता है।",
        "nav_wizard": "मार्गदर्शित जांच",
        "nav_chat": "आवाज़ और चैट",
        "nav_schemes": "योजनाएं",
        "nav_support": "मानव सहायता",
        "nav_privacy": "गोपनीयता",
        "lang_label": "भाषा",
        "footer_line": "सत्यापित योजनाएं, आसान अगले कदम और जरूरत पड़ने पर मानव सहायता।",
        "comfort_off": "A+ टेक्स्ट",
        "comfort_on": "A- टेक्स्ट",
        "hero_eyebrow": "सबके लिए सरकारी सहायता खोज",
        "hero_primary": "मार्गदर्शित जांच शुरू करें",
        "hero_secondary": "योजनाएं देखें",
        "promise_official_sources": "आधिकारिक सरकारी स्रोत",
        "promise_quick_links": "सीधे आवेदन लिंक",
        "promise_human_help": "ज़रूरत पर मानव सहायता",
        "home_heading": "बिना उलझन के सही सरकारी मदद ढूंढें।",
        "home_subtitle": "कुछ आसान सवालों के जवाब दें, सत्यापित योजना देखें और सही आधिकारिक लिंक जल्दी खोलें।",
        "home_search_placeholder": "खोजें: छात्रवृत्ति, पेंशन, स्वास्थ्य, ऋण, स्टार्टअप",
        "home_search_label": "योजना खोजें",
        "use_voice_chat": "आवाज़ या चैट का उपयोग करें",
        "metric_schemes": "योजना रिकॉर्ड उपलब्ध",
        "metric_categories": "सरल सहायता श्रेणियां",
        "metric_states": "राज्य आधारित मार्गदर्शन",
        "fast_path_label": "तेज़ रास्ता",
        "fast_path_title": "कुछ मिनटों में सही मिलान",
        "fast_path_text": "योजना का नाम पहले से जानना ज़रूरी नहीं है।",
        "comfort_label": "सुविधा",
        "comfort_title": "बड़ा टेक्स्ट और आवाज़ सहायता",
        "made_for_label": "पहली बार उपयोग करने वालों के लिए",
        "made_for_text": "बड़े कार्ड, सरल भाषा और सीधे अगले कदम।",
        "choose_need_kicker": "एक ज़रूरत चुनें",
        "choose_need_title": "एक स्पष्ट समस्या से शुरू करें",
        "how_it_works_kicker": "यह कैसे काम करता है",
        "how_it_works_title": "तीन आसान कदम",
        "comfort_section_kicker": "सुविधा",
        "comfort_section_title": "कम उम्र और अधिक उम्र दोनों के लिए आसान",
        "featured_kicker": "विश्वसनीय विकल्प",
        "featured_title": "शुरू करने के लोकप्रिय विकल्प",
        "trusted_source": "विश्वसनीय स्रोत",
        "wizard_title": "मार्गदर्शित पात्रता जांच",
        "wizard_heading": "सिर्फ वही जवाब दें जो ज़रूरी है।",
        "wizard_subtitle": "हम केवल ज़रूरी जानकारी पूछते हैं ताकि नए उपयोगकर्ता भी जल्दी और भरोसे से पूरा कर सकें।",
        "wizard_promise_1": "3 सरल चरण",
        "wizard_promise_2": "सरल भाषा",
        "wizard_promise_3": "मिलान के बाद आधिकारिक लिंक",
        "wizard_step_1": "1. मूल जानकारी",
        "wizard_step_2": "2. किसे सहायता चाहिए",
        "wizard_step_3": "3. अंतिम जांच",
        "wizard_submit": "सिफारिशें देखें",
        "wizard_side_kicker": "जानने योग्य बात",
        "wizard_side_title": "सारी जानकारी बिल्कुल सही होना ज़रूरी नहीं",
        "wizard_result_title": "आपके लिए अगले बेहतर कदम",
        "wizard_empty": "अभी कोई मज़बूत मिलान नहीं मिला। मानव सहायता अगला बेहतर कदम है।",
        "matches_found": "उपयोगी मिलान मिले",
        "next_step_label": "अगला कदम",
        "effort_label": "अनुमानित मेहनत",
        "documents_label": "दस्तावेज़",
        "documents_fallback": "नवीनतम दस्तावेज़ सूची के लिए आधिकारिक योजना पेज खोलें।",
        "chat_title": "मार्गदर्शित आवाज़ और चैट",
        "chat_heading": "स्वाभाविक रूप से बात करें। आसान जवाब पाएं।",
        "chat_subtitle": "सरल शब्दों में बोलें या लिखें। सहायक आपकी चुनी हुई भाषा में अगला कदम सुझाएगा।",
        "chat_promise_1": "लंबा फ़ॉर्म नहीं",
        "chat_promise_2": "उदाहरण पहले से दिए गए हैं",
        "chat_promise_3": "एक टैप में योजना विवरण",
        "chat_assistant_title": "जनसेतु सहायक",
        "chat_assistant_subtitle": "वैसे ही बोलें जैसे आप किसी मददगार व्यक्ति से पूछते हैं।",
        "chat_placeholder": "उदाहरण: मेरी आय 2 लाख है, मैं महाराष्ट्र से हूं और मुझे छात्रवृत्ति चाहिए",
        "chat_best_for_kicker": "कब उपयोगी है",
        "chat_best_for_title": "जब चैट आसान लगे",
        "prefer_wizard": "चरण-दर-चरण मार्गदर्शन चुनें",
        "voice_listen": "बोलें",
        "voice_stop": "रोकें",
        "voice_read": "उत्तर सुनें",
        "voice_listening": "सुन रहा है...",
        "send": "भेजें",
        "chat_intro": "अपनी उम्र, आय, राज्य और ज़रूरत बताइए। मैं सबसे उपयुक्त योजनाएं ढूंढने की कोशिश करूंगा।",
        "chat_error": "योजना सूची देखते समय कुछ गड़बड़ हुई।",
        "chat_retry": "अभी उत्तर तैयार नहीं हो पाया। कृपया फिर से कोशिश करें।",
        "chat_connection_failed": "कनेक्शन में समस्या आई। कृपया थोड़ी देर बाद फिर कोशिश करें।",
        "chat_open_details": "विवरण खोलें",
        "chat_official_source": "आधिकारिक स्रोत",
        "chat_human_title": "मानव सहायता चाहिए?",
        "chat_human_text": "कॉलबैक सहायता के लिए मानव सहायता पेज खोलें।",
        "support_request_link": "सहायता मांगें",
        "support_title": "मानव सहायता का अनुरोध",
        "support_heading": "जब यात्रा कठिन लगे, तब किसी वास्तविक व्यक्ति से मदद लें।",
        "support_subtitle": "अगर नियम मुश्किल लगें, दस्तावेज़ कम हों या आपको मार्गदर्शन चाहिए, तो यहां सहायता मांगें।",
        "support_submit": "सहायता मांगें",
        "support_success": "सहायता अनुरोध सुरक्षित हो गया है। अब कोई व्यक्ति आगे संपर्क कर सकता है।",
        "support_reasons_kicker": "अच्छे कारण",
        "support_reasons_title": "मानव सहायता लें जब",
        "schemes_title": "सत्यापित योजना खोज",
        "schemes_heading": "बिना घबराहट के विश्वसनीय योजनाएं देखें।",
        "schemes_subtitle": "आधिकारिक रिकॉर्ड खोजें, ज़रूरत के अनुसार फ़िल्टर करें और अगले कदम के साथ साफ़ विवरण पेज खोलें।",
        "catalogue_records": "रिकॉर्ड इस सूची में",
        "simple_categories": "सरल श्रेणियां",
        "current_page": "वर्तमान पेज",
        "schemes_search_placeholder": "योजना, लाभ, मंत्रालय, टैग या ज़रूरत से खोजें",
        "filter_all_categories": "सभी श्रेणियां",
        "filter_all_states": "सभी राज्य",
        "apply_filters": "फ़िल्टर लागू करें",
        "what_to_do_next": "अब क्या करें",
        "official_source_pending": "आधिकारिक स्रोत लंबित",
        "no_matching_schemes": "अभी कोई मिलती योजना नहीं मिली",
        "no_matching_schemes_help": "छात्रवृत्ति, स्वास्थ्य, पेंशन, व्यवसाय, नौकरी या दिव्यांग सहायता जैसे शब्द आज़माएं।",
        "previous": "पिछला",
        "next": "अगला",
        "page_of": "पेज {current} / {total}",
        "scheme_details_kicker": "योजना विवरण",
        "quick_links_kicker": "त्वरित लिंक",
        "quick_links_title": "सही जगह जल्दी खोलें",
        "detail_apply_card_kicker": "अभी शुरू करें",
        "detail_apply_card_title": "सबसे सुरक्षित आधिकारिक लिंक से शुरू करें",
        "detail_apply_card_text": "पहले आधिकारिक स्रोत खोलें, फिर नीचे दिए दस्तावेज़ तैयार रखें।",
        "detail_source_label": "स्रोत",
        "detail_eligibility_label": "पात्रता",
        "detail_benefits_label": "लाभ",
        "detail_apply_label": "कैसे आवेदन करें",
        "detail_last_verified_label": "अंतिम सत्यापन",
        "detail_where_to_apply_label": "कहां आवेदन करें",
        "detail_effort_level_label": "मेहनत का स्तर",
        "detail_coverage_label": "कवरेज",
        "detail_documents_kicker": "दस्तावेज़",
        "detail_documents_title": "इन्हें तैयार रखें",
        "detail_faq_kicker": "सामान्य प्रश्न",
        "detail_faq_title": "आम सवाल",
        "detail_documents_fallback": "नवीनतम आवश्यक दस्तावेज़ देखने के लिए आधिकारिक पेज खोलें।",
        "detail_faq_fallback": "इस योजना के लिए अभी कोई प्रश्न उपलब्ध नहीं है।",
        "open_official_page": "आधिकारिक पेज",
        "not_set": "उपलब्ध नहीं",
        "detail_apply_fallback": "ऊपर दिया गया आधिकारिक पेज देखें।",
        "scheme_apply_fallback": "नवीनतम आवेदन जानकारी के लिए आधिकारिक पेज खोलें।",
        "privacy_title": "गोपनीयता और जिम्मेदार उपयोग",
        "privacy_subtitle": "यह सेवा केवल वही जानकारी रखती है जो सहायता सुधारने, गुणवत्ता जांचने और अनुरोधों पर कार्य करने के लिए ज़रूरी है।",
        "privacy_store_title": "यह सेवा क्या संग्रहीत करती है",
        "privacy_use_title": "डेटा का उपयोग कैसे होना चाहिए",
        "ops_title": "ऑपरेशंस डैशबोर्ड",
        "ops_subtitle": "अनुत्तरित अनुरोध, पुरानी योजना प्रविष्टियां, लिंक समस्याएं और मांग रुझान देखें।",
        "select_state": "राज्य चुनें",
        "select_district": "जिला चुनें",
    },
    "mr": {
        "brand_name": "जनसेतु",
        "brand_tagline": "सरकारी मदत मार्गदर्शक",
        "meta_description": "जनसेतु भारतातील लोकांना सत्यापित सरकारी योजना, स्पष्ट पुढची पावले आणि अधिकृत अर्ज दुवे सोप्या भाषेत शोधायला मदत करते.",
        "nav_wizard": "मार्गदर्शित तपासणी",
        "nav_chat": "आवाज आणि चॅट",
        "nav_schemes": "योजना",
        "nav_support": "मानवी मदत",
        "nav_privacy": "गोपनीयता",
        "lang_label": "भाषा",
        "footer_line": "सत्यापित योजना, सोपी पुढची पावले आणि गरज पडल्यास मानवी मदत.",
        "comfort_off": "A+ मजकूर",
        "comfort_on": "A- मजकूर",
        "hero_eyebrow": "सगळ्यांसाठी सरकारी मदत शोध",
        "hero_primary": "मार्गदर्शित तपासणी सुरू करा",
        "hero_secondary": "योजना पाहा",
        "promise_official_sources": "अधिकृत सरकारी स्रोत",
        "promise_quick_links": "त्वरित अर्ज दुवे",
        "promise_human_help": "गरजेच्या वेळी मानवी मदत",
        "home_heading": "गोंधळ न होता योग्य सरकारी मदत शोधा.",
        "home_subtitle": "काही सोपे प्रश्न भरा, सत्यापित योजना पाहा आणि योग्य अधिकृत लिंक पटकन उघडा.",
        "home_search_placeholder": "शोधा: शिष्यवृत्ती, पेन्शन, आरोग्य, कर्ज, स्टार्टअप",
        "home_search_label": "योजना शोधा",
        "use_voice_chat": "आवाज किंवा चॅट वापरा",
        "metric_schemes": "योजना नोंदी उपलब्ध",
        "metric_categories": "सोप्या मदत श्रेण्या",
        "metric_states": "राज्य-आधारित मार्गदर्शन",
        "fast_path_label": "जलद मार्ग",
        "fast_path_title": "काही मिनिटांत योग्य जुळणी",
        "fast_path_text": "योजनेचे नाव आधी माहीत असणे गरजेचे नाही.",
        "comfort_label": "सोय",
        "comfort_title": "मोठा मजकूर आणि आवाज मदत",
        "made_for_label": "पहिल्यांदा वापरणाऱ्यांसाठी",
        "made_for_text": "मोठी कार्डे, सोपी भाषा आणि स्पष्ट पुढची पावले.",
        "choose_need_kicker": "एक गरज निवडा",
        "choose_need_title": "एका स्पष्ट समस्येपासून सुरुवात करा",
        "how_it_works_kicker": "हे कसे काम करते",
        "how_it_works_title": "तीन सोपी पावले",
        "comfort_section_kicker": "सोय",
        "comfort_section_title": "लहान आणि मोठ्या वयाच्या दोघांसाठी सोपे",
        "featured_kicker": "विश्वासार्ह पर्याय",
        "featured_title": "सुरुवातीसाठी लोकप्रिय पर्याय",
        "trusted_source": "विश्वासार्ह स्रोत",
        "wizard_title": "मार्गदर्शित पात्रता तपासणी",
        "wizard_heading": "फक्त आवश्यक तेवढीच उत्तरे द्या.",
        "wizard_subtitle": "आम्ही फक्त उपयोगाची माहिती विचारतो, त्यामुळे नवीन वापरकर्तेही हे पटकन आणि आत्मविश्वासाने पूर्ण करू शकतात.",
        "wizard_promise_1": "3 सोपे टप्पे",
        "wizard_promise_2": "सोप्या भाषेत",
        "wizard_promise_3": "जुळणीनंतर अधिकृत दुवे",
        "wizard_step_1": "1. मूलभूत माहिती",
        "wizard_step_2": "2. कोणाला मदत हवी आहे",
        "wizard_step_3": "3. अंतिम तपासणी",
        "wizard_submit": "शिफारसी पाहा",
        "wizard_side_kicker": "महत्त्वाची माहिती",
        "wizard_side_title": "सगळी माहिती परफेक्ट असणे गरजेचे नाही",
        "wizard_result_title": "तुमच्यासाठी पुढची चांगली पावले",
        "wizard_empty": "आत्ता ठोस जुळणी मिळाली नाही. मानवी मदत पुढचे योग्य पाऊल आहे.",
        "matches_found": "उपयोगी जुळण्या मिळाल्या",
        "next_step_label": "पुढचे पाऊल",
        "effort_label": "अंदाजे मेहनत",
        "documents_label": "दस्तावेज",
        "documents_fallback": "नवीनतम दस्तावेजांची यादी पाहण्यासाठी अधिकृत योजना पेज उघडा.",
        "chat_title": "मार्गदर्शित आवाज आणि चॅट",
        "chat_heading": "नैसर्गिकपणे बोला. सोपे उत्तर मिळवा.",
        "chat_subtitle": "सोप्या शब्दांत बोला किंवा लिहा. सहाय्यक तुमच्या निवडलेल्या भाषेनुसार पुढचे पाऊल सुचवेल.",
        "chat_promise_1": "मोठा फॉर्म नाही",
        "chat_promise_2": "उदाहरणे आधीच दिली आहेत",
        "chat_promise_3": "एका टॅपमध्ये योजना तपशील",
        "chat_assistant_title": "जनसेतु सहाय्यक",
        "chat_assistant_subtitle": "तुम्ही जसे एखाद्या मदत करणाऱ्या व्यक्तीला विचाराल तसे बोला.",
        "chat_placeholder": "उदाहरण: माझे उत्पन्न 2 लाख आहे, मी महाराष्ट्रातून आहे आणि मला शिष्यवृत्ती हवी आहे",
        "chat_best_for_kicker": "यासाठी योग्य",
        "chat_best_for_title": "जेव्हा चॅट सोपी वाटते",
        "prefer_wizard": "टप्प्याटप्प्याने मार्गदर्शन निवडा",
        "voice_listen": "बोला",
        "voice_stop": "थांबा",
        "voice_read": "उत्तर ऐका",
        "voice_listening": "ऐकत आहे...",
        "send": "पाठवा",
        "chat_intro": "तुमचे वय, उत्पन्न, राज्य आणि गरज सांगा. मी सर्वात योग्य योजना शोधण्याचा प्रयत्न करेन.",
        "chat_error": "योजना यादी तपासताना काही अडचण आली.",
        "chat_retry": "आत्ता उत्तर तयार झाले नाही. कृपया पुन्हा प्रयत्न करा.",
        "chat_connection_failed": "कनेक्शनमध्ये अडचण आली. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.",
        "chat_open_details": "तपशील उघडा",
        "chat_official_source": "अधिकृत स्रोत",
        "chat_human_title": "मानवी मदत हवी आहे?",
        "chat_human_text": "कॉलबॅक सहाय्यासाठी मानवी मदत पेज उघडा.",
        "support_request_link": "मदत मागा",
        "support_title": "मानवी मदतीची विनंती",
        "support_heading": "प्रवास कठीण वाटत असल्यास खऱ्या व्यक्तीकडून मदत घ्या.",
        "support_subtitle": "नियम कठीण वाटले, दस्तावेज कमी असले किंवा मार्गदर्शन हवे असल्यास येथे मदत मागा.",
        "support_submit": "मदत मागा",
        "support_success": "मदतीची विनंती जतन झाली आहे. आता एखादी व्यक्ती पुढे संपर्क करू शकते.",
        "support_reasons_kicker": "योग्य कारणे",
        "support_reasons_title": "मानवी मदत घ्या जेव्हा",
        "schemes_title": "सत्यापित योजना शोध",
        "schemes_heading": "गोंधळ न होता विश्वासार्ह योजना पाहा.",
        "schemes_subtitle": "अधिकृत नोंदी शोधा, गरजेनुसार फिल्टर करा आणि पुढच्या पावलांसह स्पष्ट तपशील पेज उघडा.",
        "catalogue_records": "नोंदी या यादीत",
        "simple_categories": "सोप्या श्रेण्या",
        "current_page": "सध्याचे पान",
        "schemes_search_placeholder": "योजना, लाभ, मंत्रालय, टॅग किंवा गरजेनुसार शोधा",
        "filter_all_categories": "सर्व श्रेण्या",
        "filter_all_states": "सर्व राज्ये",
        "apply_filters": "फिल्टर लागू करा",
        "what_to_do_next": "आता काय करायचे",
        "official_source_pending": "अधिकृत स्रोत प्रलंबित",
        "no_matching_schemes": "आत्ता जुळणाऱ्या योजना मिळाल्या नाहीत",
        "no_matching_schemes_help": "शिष्यवृत्ती, आरोग्य, पेन्शन, व्यवसाय, नोकरी किंवा दिव्यांग मदत असे शब्द वापरून पाहा.",
        "previous": "मागील",
        "next": "पुढील",
        "page_of": "पान {current} / {total}",
        "scheme_details_kicker": "योजना तपशील",
        "quick_links_kicker": "त्वरित दुवे",
        "quick_links_title": "योग्य जागा पटकन उघडा",
        "detail_apply_card_kicker": "आता सुरू करा",
        "detail_apply_card_title": "सर्वात सुरक्षित अधिकृत दुव्यापासून सुरुवात करा",
        "detail_apply_card_text": "सुरुवातीला अधिकृत स्रोत उघडा आणि नंतर खालील दस्तावेज तयार ठेवा.",
        "detail_source_label": "स्रोत",
        "detail_eligibility_label": "पात्रता",
        "detail_benefits_label": "फायदे",
        "detail_apply_label": "अर्ज कसा करायचा",
        "detail_last_verified_label": "शेवटची पडताळणी",
        "detail_where_to_apply_label": "कोठे अर्ज करायचा",
        "detail_effort_level_label": "मेहनतीची पातळी",
        "detail_coverage_label": "कव्हरेज",
        "detail_documents_kicker": "दस्तावेज",
        "detail_documents_title": "हे तयार ठेवा",
        "detail_faq_kicker": "सामान्य प्रश्न",
        "detail_faq_title": "सामान्य शंका",
        "detail_documents_fallback": "नवीनतम आवश्यक दस्तावेज पाहण्यासाठी अधिकृत पेज उघडा.",
        "detail_faq_fallback": "या योजनेसाठी सध्या कोणतेही प्रश्न उपलब्ध नाहीत.",
        "open_official_page": "अधिकृत पेज",
        "not_set": "उपलब्ध नाही",
        "detail_apply_fallback": "वरील अधिकृत पेज पाहा.",
        "scheme_apply_fallback": "नवीनतम अर्ज माहितीसाठी अधिकृत पेज उघडा.",
        "privacy_title": "गोपनीयता आणि जबाबदार वापर",
        "privacy_subtitle": "ही सेवा फक्त मदत सुधारण्यासाठी, गुणवत्ता तपासण्यासाठी आणि विनंत्यांवर कार्य करण्यासाठी लागणारी माहिती साठवते.",
        "privacy_store_title": "ही सेवा काय साठवते",
        "privacy_use_title": "डेटाचा वापर कसा करावा",
        "ops_title": "ऑपरेशन्स डॅशबोर्ड",
        "ops_subtitle": "अनुत्तरित विनंत्या, जुन्या योजना नोंदी, लिंक अडचणी आणि मागणीचे कल पहा.",
        "select_state": "राज्य निवडा",
        "select_district": "जिल्हा निवडा",
    },
}


CONTENT_LISTS = {
    "home_needs": {
        "en": [
            {"label": "Study or scholarship", "category": "education", "tagline": "School, college, training, scholarship"},
            {"label": "Money support", "category": "financial", "tagline": "Loans, grants, pension, direct help"},
            {"label": "Health or maternity", "category": "health", "tagline": "Pregnancy, treatment, nutrition, care"},
            {"label": "Jobs or skills", "category": "employment", "tagline": "Training, livelihood, entrepreneurship"},
            {"label": "Family and care", "category": "empowerment", "tagline": "Women, child, disability, welfare"},
        ],
        "hi": [
            {"label": "पढ़ाई या छात्रवृत्ति", "category": "education", "tagline": "स्कूल, कॉलेज, प्रशिक्षण, छात्रवृत्ति"},
            {"label": "आर्थिक सहायता", "category": "financial", "tagline": "ऋण, अनुदान, पेंशन, सीधी मदद"},
            {"label": "स्वास्थ्य या मातृत्व", "category": "health", "tagline": "गर्भावस्था, इलाज, पोषण, देखभाल"},
            {"label": "नौकरी या कौशल", "category": "employment", "tagline": "प्रशिक्षण, आजीविका, उद्यमिता"},
            {"label": "परिवार और देखभाल", "category": "empowerment", "tagline": "महिला, बच्चा, दिव्यांग, कल्याण"},
        ],
        "mr": [
            {"label": "शिक्षण किंवा शिष्यवृत्ती", "category": "education", "tagline": "शाळा, कॉलेज, प्रशिक्षण, शिष्यवृत्ती"},
            {"label": "आर्थिक मदत", "category": "financial", "tagline": "कर्ज, अनुदान, पेन्शन, थेट मदत"},
            {"label": "आरोग्य किंवा मातृत्व", "category": "health", "tagline": "गर्भावस्था, उपचार, पोषण, काळजी"},
            {"label": "नोकरी किंवा कौशल्य", "category": "employment", "tagline": "प्रशिक्षण, उपजीविका, उद्योजकता"},
            {"label": "कुटुंब आणि काळजी", "category": "empowerment", "tagline": "महिला, बालक, दिव्यांग, कल्याण"},
        ],
    },
    "home_steps": {
        "en": [
            "Pick what kind of help you need.",
            "Answer a few basic questions like age, state, district, and income band.",
            "Open the matched scheme and follow the next steps or ask for human help.",
        ],
        "hi": [
            "पहले चुनें कि आपको किस तरह की मदद चाहिए।",
            "उम्र, राज्य, जिला और आय वर्ग जैसे कुछ आसान सवालों के जवाब दें।",
            "मिली हुई योजना खोलें और अगले कदम देखें या मानव सहायता मांगें।",
        ],
        "mr": [
            "सुरुवातीला तुम्हाला कोणत्या प्रकारची मदत हवी आहे ते निवडा.",
            "वय, राज्य, जिल्हा आणि उत्पन्न गट यांसारखे काही सोपे प्रश्न भरा.",
            "मिळालेली योजना उघडा आणि पुढची पावले पहा किंवा मानवी मदत मागा.",
        ],
    },
    "home_comfort_points": {
        "en": [
            "Large buttons and readable spacing.",
            "Voice and chat support for people who do not want forms.",
            "Quick links instead of long confusing text.",
            "Human support when the answer is unclear.",
        ],
        "hi": [
            "बड़े बटन और पढ़ने में आसान दूरी।",
            "जो लोग फ़ॉर्म नहीं भरना चाहते उनके लिए आवाज़ और चैट सहायता।",
            "लंबे कठिन टेक्स्ट की जगह सीधे लिंक।",
            "उत्तर स्पष्ट न हो तो मानव सहायता।",
        ],
        "mr": [
            "मोठी बटणे आणि वाचण्यास सोपी मांडणी.",
            "फॉर्म नको असणाऱ्यांसाठी आवाज आणि चॅट मदत.",
            "मोठ्या कठीण मजकुराऐवजी थेट दुवे.",
            "उत्तर स्पष्ट नसल्यास मानवी मदत.",
        ],
    },
    "need_focus_options": {
        "en": [
            {"value": "farmer", "label": "Farmer", "hint": "Crop, subsidy, irrigation, rural support"},
            {"value": "student", "label": "Student", "hint": "Scholarship, stipend, study help"},
            {"value": "older", "label": "Older person", "hint": "Pension, senior support, care"},
            {"value": "job_seeker", "label": "Job seeker", "hint": "Training, jobs, livelihood"},
            {"value": "stipend", "label": "Stipend", "hint": "Education or training money"},
            {"value": "housing", "label": "House scheme", "hint": "Home, shelter, housing support"},
            {"value": "food", "label": "Food support", "hint": "Ration, nutrition, public food help"},
            {"value": "businessman", "label": "Business person", "hint": "Loan, startup, self-employment"},
        ],
        "hi": [
            {"value": "farmer", "label": "किसान", "hint": "फसल, सब्सिडी, सिंचाई, ग्रामीण सहायता"},
            {"value": "student", "label": "छात्र", "hint": "छात्रवृत्ति, स्टाइपेंड, पढ़ाई सहायता"},
            {"value": "older", "label": "बुज़ुर्ग", "hint": "पेंशन, वरिष्ठ सहायता, देखभाल"},
            {"value": "job_seeker", "label": "नौकरी चाहने वाला", "hint": "प्रशिक्षण, नौकरी, आजीविका"},
            {"value": "stipend", "label": "स्टाइपेंड", "hint": "पढ़ाई या प्रशिक्षण के लिए धन"},
            {"value": "housing", "label": "घर योजना", "hint": "घर, आश्रय, आवास सहायता"},
            {"value": "food", "label": "खाद्य सहायता", "hint": "राशन, पोषण, सार्वजनिक खाद्य सहायता"},
            {"value": "businessman", "label": "व्यवसायी", "hint": "ऋण, स्टार्टअप, स्वरोज़गार"},
        ],
        "mr": [
            {"value": "farmer", "label": "शेतकरी", "hint": "पीक, अनुदान, सिंचन, ग्रामीण मदत"},
            {"value": "student", "label": "विद्यार्थी", "hint": "शिष्यवृत्ती, स्टायपेंड, शिक्षण मदत"},
            {"value": "older", "label": "ज्येष्ठ नागरिक", "hint": "पेन्शन, ज्येष्ठ मदत, काळजी"},
            {"value": "job_seeker", "label": "नोकरी शोधणारा", "hint": "प्रशिक्षण, नोकरी, उपजीविका"},
            {"value": "stipend", "label": "स्टायपेंड", "hint": "शिक्षण किंवा प्रशिक्षणासाठी पैसे"},
            {"value": "housing", "label": "घर योजना", "hint": "घर, निवारा, गृह मदत"},
            {"value": "food", "label": "अन्न मदत", "hint": "रेशन, पोषण, सार्वजनिक अन्न मदत"},
            {"value": "businessman", "label": "व्यवसायिक", "hint": "कर्ज, स्टार्टअप, स्वयंरोजगार"},
        ],
    },
    "separate_features": {
        "en": [
            "Cleaner homepage with only the main action at the top.",
            "Latest official scheme news shown in one separate news column.",
            "Guided check starts with real-life need options instead of confusing labels.",
        ],
        "hi": [
            "ऊपर केवल मुख्य कार्रवाई के साथ अधिक साफ़ होमपेज।",
            "एक अलग समाचार कॉलम में नवीनतम आधिकारिक योजना अपडेट।",
            "मार्गदर्शित जांच वास्तविक जीवन विकल्पों से शुरू होती है।",
        ],
        "mr": [
            "वरती फक्त मुख्य कृतीसह अधिक स्वच्छ होमपेज.",
            "एका वेगळ्या न्यूज कॉलममध्ये ताज्या अधिकृत योजना अपडेट्स.",
            "मार्गदर्शित तपासणी गोंधळाऐवजी प्रत्यक्ष गरज पर्यायांपासून सुरू होते.",
        ],
    },
    "chat_prompts": {
        "en": [
            "I am a student from Maharashtra and need scholarship support.",
            "My mother is pregnant and we need maternity scheme help.",
            "I want to start a small business and need a government loan.",
            "My father is a senior citizen. Please show pension support.",
        ],
        "hi": [
            "मैं महाराष्ट्र से छात्र हूं और मुझे छात्रवृत्ति सहायता चाहिए।",
            "मेरी मां गर्भवती हैं और हमें मातृत्व योजना की मदद चाहिए।",
            "मैं छोटा व्यवसाय शुरू करना चाहता हूं और मुझे सरकारी ऋण चाहिए।",
            "मेरे पिता वरिष्ठ नागरिक हैं। कृपया पेंशन सहायता दिखाइए।",
        ],
        "mr": [
            "मी महाराष्ट्रातील विद्यार्थी आहे आणि मला शिष्यवृत्ती मदत हवी आहे.",
            "माझी आई गर्भवती आहे आणि आम्हाला मातृत्व योजनेची मदत हवी आहे.",
            "मला छोटा व्यवसाय सुरू करायचा आहे आणि मला सरकारी कर्ज हवे आहे.",
            "माझे वडील ज्येष्ठ नागरिक आहेत. कृपया पेन्शन मदत दाखवा.",
        ],
    },
    "chat_best_for": {
        "en": [
            "You do not know which scheme category to choose.",
            "You want to speak in your own words.",
            "You need a quick answer before filling the wizard.",
            "You want voice support for reading replies aloud.",
        ],
        "hi": [
            "आपको नहीं पता कि कौन-सी योजना श्रेणी चुनें।",
            "आप अपनी भाषा में बोलकर बताना चाहते हैं।",
            "विज़ार्ड भरने से पहले जल्दी जवाब चाहिए।",
            "उत्तर सुनने के लिए आवाज़ सहायता चाहिए।",
        ],
        "mr": [
            "कोणती योजना श्रेणी निवडायची हे माहित नाही.",
            "तुम्हाला स्वतःच्या शब्दांत सांगायचे आहे.",
            "विझार्ड भरण्यापूर्वी पटकन उत्तर हवे आहे.",
            "उत्तर मोठ्याने ऐकण्यासाठी आवाज मदत हवी आहे.",
        ],
    },
    "wizard_tips": {
        "en": [
            "If you do not know the exact income, choose the closest band.",
            "If documents are not ready, we will still show the scheme and next steps.",
            "If nothing matches strongly, we will suggest human help instead of guessing.",
        ],
        "hi": [
            "अगर सही आय नहीं पता, तो सबसे नज़दीकी आय वर्ग चुनें।",
            "दस्तावेज़ तैयार न हों, तब भी हम योजना और अगले कदम दिखाएंगे।",
            "अगर स्पष्ट मिलान न मिले, तो अनुमान लगाने के बजाय मानव सहायता सुझाई जाएगी।",
        ],
        "mr": [
            "अचूक उत्पन्न माहित नसेल तर जवळचा गट निवडा.",
            "दस्तावेज तयार नसले तरी आम्ही योजना आणि पुढची पावले दाखवू.",
            "ठोस जुळणी न मिळाल्यास अंदाज न बांधता मानवी मदत सुचवली जाईल.",
        ],
    },
    "support_reasons": {
        "en": [
            "You are not sure which scheme is the right one.",
            "You need help with documents or portal login.",
            "You want callback support in simple language.",
            "The case involves disability, old age, pregnancy, or urgent need.",
        ],
        "hi": [
            "आपको समझ नहीं आ रहा कि सही योजना कौन-सी है।",
            "दस्तावेज़ या पोर्टल लॉगिन में मदद चाहिए।",
            "सरल भाषा में कॉलबैक सहायता चाहिए।",
            "मामला दिव्यांगता, बुज़ुर्ग, गर्भावस्था या तात्कालिक ज़रूरत से जुड़ा है।",
        ],
        "mr": [
            "योग्य योजना कोणती हे समजत नाही.",
            "दस्तावेज किंवा पोर्टल लॉगिनसाठी मदत हवी आहे.",
            "सोप्या भाषेत कॉलबॅक मदत हवी आहे.",
            "प्रकरण दिव्यांगता, वृद्ध, गर्भावस्था किंवा तातडीच्या गरजेशी संबंधित आहे.",
        ],
    },
    "privacy_store_items": {
        "en": [
            "Chat questions and AI responses for quality review.",
            "Eligibility checks and recommended schemes.",
            "Human support requests for callback and case handling.",
            "Operational audit logs for monitoring and admin review.",
        ],
        "hi": [
            "गुणवत्ता समीक्षा के लिए चैट प्रश्न और AI उत्तर।",
            "पात्रता जांच और सुझाई गई योजनाएं।",
            "कॉलबैक और केस प्रबंधन के लिए मानव सहायता अनुरोध।",
            "निगरानी और एडमिन समीक्षा के लिए परिचालन ऑडिट लॉग।",
        ],
        "mr": [
            "गुणवत्ता तपासणीसाठी चॅट प्रश्न आणि AI उत्तरे.",
            "पात्रता तपासणी आणि सुचवलेल्या योजना.",
            "कॉलबॅक आणि केस हाताळणीसाठी मानवी मदत विनंत्या.",
            "निगराणी आणि अॅडमिन पुनरावलोकनासाठी ऑपरेशनल ऑडिट लॉग.",
        ],
    },
    "privacy_use_items": {
        "en": [
            "Only for service delivery, debugging, and user follow-up.",
            "Do not use stored records for unrelated profiling or advertising.",
            "Remove or anonymize personally identifying data before broader analytics use.",
            "Publish a formal privacy policy and data retention window before production launch.",
        ],
        "hi": [
            "केवल सेवा, डीबगिंग और उपयोगकर्ता फॉलो-अप के लिए उपयोग करें।",
            "संग्रहीत रिकॉर्ड का उपयोग असंबंधित प्रोफाइलिंग या विज्ञापन के लिए न करें।",
            "विस्तृत विश्लेषण से पहले व्यक्तिगत पहचान वाली जानकारी हटाएं या अनाम करें।",
            "प्रोडक्शन लॉन्च से पहले औपचारिक गोपनीयता नीति और डेटा अवधि प्रकाशित करें।",
        ],
        "mr": [
            "फक्त सेवा, डीबगिंग आणि वापरकर्ता फॉलो-अपसाठी वापरा.",
            "साठवलेले रेकॉर्ड असंबंधित प्रोफाइलिंग किंवा जाहिरातींसाठी वापरू नका.",
            "मोठ्या विश्लेषणापूर्वी वैयक्तिक ओळख दर्शवणारी माहिती काढून टाका किंवा अनामिक करा.",
            "प्रॉडक्शन लॉन्चपूर्वी औपचारिक गोपनीयता धोरण आणि डेटा ठेवण्याची मर्यादा प्रकाशित करा.",
        ],
    },
}


FIELD_LABELS = {
    "en": {
        "age": "Age",
        "state": "State",
        "district": "District",
        "support_need": "Main need",
        "income_band": "Income band",
        "gender": "Gender",
        "residence_type": "Residence type",
        "is_student": "Student or learner",
        "is_mother": "Pregnancy or mother care",
        "is_entrepreneur": "Business or self-employment",
        "has_disability": "Disability support needed",
        "annual_income": "Annual income",
        "caste_category": "Caste category",
        "document_readiness": "Document readiness",
        "notes": "Anything important we should know? (optional)",
        "name": "Name",
        "phone_number": "Phone number",
        "email": "Email (optional)",
        "support_type": "Type of help",
        "message": "What do you need help with?",
    },
    "hi": {
        "age": "उम्र",
        "state": "राज्य",
        "district": "जिला",
        "support_need": "मुख्य ज़रूरत",
        "income_band": "आय वर्ग",
        "gender": "लिंग",
        "residence_type": "निवास प्रकार",
        "is_student": "छात्र या शिक्षार्थी",
        "is_mother": "गर्भावस्था या मातृ देखभाल",
        "is_entrepreneur": "व्यवसाय या स्वरोज़गार",
        "has_disability": "दिव्यांग सहायता चाहिए",
        "annual_income": "वार्षिक आय",
        "caste_category": "जाति श्रेणी",
        "document_readiness": "दस्तावेज़ तैयारी",
        "notes": "कोई ज़रूरी बात जो हमें जाननी चाहिए? (वैकल्पिक)",
        "name": "नाम",
        "phone_number": "फ़ोन नंबर",
        "email": "ईमेल (वैकल्पिक)",
        "support_type": "सहायता का प्रकार",
        "message": "आपको किस बात में मदद चाहिए?",
    },
    "mr": {
        "age": "वय",
        "state": "राज्य",
        "district": "जिल्हा",
        "support_need": "मुख्य गरज",
        "income_band": "उत्पन्न गट",
        "gender": "लिंग",
        "residence_type": "निवास प्रकार",
        "is_student": "विद्यार्थी किंवा शिकणारा",
        "is_mother": "गर्भावस्था किंवा मातृत्व काळजी",
        "is_entrepreneur": "व्यवसाय किंवा स्वयंरोजगार",
        "has_disability": "दिव्यांग मदत हवी आहे",
        "annual_income": "वार्षिक उत्पन्न",
        "caste_category": "जातीची श्रेणी",
        "document_readiness": "दस्तावेज तयारी",
        "notes": "आम्हाला माहित असावी अशी काही महत्त्वाची गोष्ट? (पर्यायी)",
        "name": "नाव",
        "phone_number": "फोन नंबर",
        "email": "ईमेल (पर्यायी)",
        "support_type": "मदतीचा प्रकार",
        "message": "तुम्हाला कोणत्या गोष्टीत मदत हवी आहे?",
    },
}


FIELD_CHOICES = {
    "support_need": {
        "en": [
            ("education", "Education"),
            ("financial", "Financial Support"),
            ("health", "Health"),
            ("agriculture", "Agriculture"),
            ("employment", "Jobs and Skills"),
            ("empowerment", "Family and Welfare"),
            ("other", "Other"),
        ],
        "hi": [
            ("education", "शिक्षा"),
            ("financial", "आर्थिक सहायता"),
            ("health", "स्वास्थ्य"),
            ("agriculture", "कृषि"),
            ("employment", "नौकरी और कौशल"),
            ("empowerment", "परिवार और कल्याण"),
            ("other", "अन्य"),
        ],
        "mr": [
            ("education", "शिक्षण"),
            ("financial", "आर्थिक मदत"),
            ("health", "आरोग्य"),
            ("agriculture", "शेती"),
            ("employment", "नोकरी आणि कौशल्य"),
            ("empowerment", "कुटुंब आणि कल्याण"),
            ("other", "इतर"),
        ],
    },
    "support_type": {
        "en": [
            ("ngo_worker", "NGO worker"),
            ("shg_volunteer", "SHG volunteer"),
            ("callback", "Support callback"),
        ],
        "hi": [
            ("ngo_worker", "एनजीओ कार्यकर्ता"),
            ("shg_volunteer", "एसएचजी स्वयंसेवक"),
            ("callback", "कॉलबैक सहायता"),
        ],
        "mr": [
            ("ngo_worker", "एनजीओ कार्यकर्ता"),
            ("shg_volunteer", "एसएचजी स्वयंसेवक"),
            ("callback", "कॉलबॅक मदत"),
        ],
    },
    "income_band": {
        "en": [
            ("under_1l", "Under Rs 1 lakh"),
            ("under_2l", "Under Rs 2 lakh"),
            ("under_5l", "Under Rs 5 lakh"),
            ("under_8l", "Under Rs 8 lakh"),
            ("above_8l", "Above Rs 8 lakh"),
        ],
        "hi": [
            ("under_1l", "1 लाख रुपये से कम"),
            ("under_2l", "2 लाख रुपये से कम"),
            ("under_5l", "5 लाख रुपये से कम"),
            ("under_8l", "8 लाख रुपये से कम"),
            ("above_8l", "8 लाख रुपये से अधिक"),
        ],
        "mr": [
            ("under_1l", "1 लाख रुपयांखाली"),
            ("under_2l", "2 लाख रुपयांखाली"),
            ("under_5l", "5 लाख रुपयांखाली"),
            ("under_8l", "8 लाख रुपयांखाली"),
            ("above_8l", "8 लाख रुपयांपेक्षा जास्त"),
        ],
    },
    "gender": {
        "en": [
            ("female", "Female"),
            ("male", "Male"),
            ("any", "Prefer not to say"),
        ],
        "hi": [
            ("female", "महिला"),
            ("male", "पुरुष"),
            ("any", "नहीं बताना चाहते"),
        ],
        "mr": [
            ("female", "महिला"),
            ("male", "पुरुष"),
            ("any", "सांगू इच्छित नाही"),
        ],
    },
    "residence_type": {
        "en": [
            ("rural", "Rural"),
            ("urban", "Urban"),
            ("semi_urban", "Semi Urban"),
        ],
        "hi": [
            ("rural", "ग्रामीण"),
            ("urban", "शहरी"),
            ("semi_urban", "अर्ध-शहरी"),
        ],
        "mr": [
            ("rural", "ग्रामीण"),
            ("urban", "शहरी"),
            ("semi_urban", "अर्ध-शहरी"),
        ],
    },
    "caste_category": {
        "en": [
            ("general", "General"),
            ("sc", "SC"),
            ("st", "ST"),
            ("obc", "OBC"),
            ("ews", "EWS"),
            ("minority", "Minority"),
            ("other", "Other"),
        ],
        "hi": [
            ("general", "सामान्य"),
            ("sc", "एससी"),
            ("st", "एसटी"),
            ("obc", "ओबीसी"),
            ("ews", "ईडब्ल्यूएस"),
            ("minority", "अल्पसंख्यक"),
            ("other", "अन्य"),
        ],
        "mr": [
            ("general", "सामान्य"),
            ("sc", "एससी"),
            ("st", "एसटी"),
            ("obc", "ओबीसी"),
            ("ews", "ईडब्ल्यूएस"),
            ("minority", "अल्पसंख्यक"),
            ("other", "इतर"),
        ],
    },
    "document_readiness": {
        "en": [
            ("ready", "All documents ready"),
            ("partial", "Some documents ready"),
            ("not_ready", "Need document help"),
        ],
        "hi": [
            ("ready", "सभी दस्तावेज़ तैयार"),
            ("partial", "कुछ दस्तावेज़ तैयार"),
            ("not_ready", "दस्तावेज़ सहायता चाहिए"),
        ],
        "mr": [
            ("ready", "सर्व दस्तावेज तयार"),
            ("partial", "काही दस्तावेज तयार"),
            ("not_ready", "दस्तावेज मदत हवी आहे"),
        ],
    },
}


def _normalize_lang(lang: str) -> str:
    if lang in SUPPORTED_LANGUAGES:
        return lang
    return "en"


def get_ui_strings(lang: str):
    normalized = _normalize_lang(lang)
    strings = dict(UI_STRINGS["en"])
    strings.update(UI_STRINGS.get(normalized, {}))
    return strings


def get_content_list(name: str, lang: str):
    normalized = _normalize_lang(lang)
    content = CONTENT_LISTS.get(name, {})
    return content.get(normalized, content.get("en", []))


def get_field_labels(lang: str):
    normalized = _normalize_lang(lang)
    labels = dict(FIELD_LABELS["en"])
    labels.update(FIELD_LABELS.get(normalized, {}))
    return labels


def get_field_choices(field_name: str, lang: str):
    normalized = _normalize_lang(lang)
    field_map = FIELD_CHOICES.get(field_name, {})
    return field_map.get(normalized, field_map.get("en", []))
